### PR TITLE
Travis tests for windows

### PR DESCRIPTION
**Pull request by trichter**
Fortran compilation on travis is now working for another package of mine. Let's see if it is also working for telewavesim with its LAPACK pitfall.

### CODE REVIEW

**Comment by paudetseis** [comment]
The 'fortran-compiler' worked, but the Windows OS install fails, it seems due to `pip`. Here's the message on the failed CI build (around line 2534 and below) - any insight?:

[telewavesim_windows_tests.txt](https://github.com/paudetseis/Telewavesim/files/4272738/telewavesim_windows_tests.txt)

**Comment by trichter** [comment]
Yes, I have seen the error and will have a look.

**Comment by trichter** [comment]
The fortran compile used in windows appears to be more restrictive.

https://travis-ci.com/paudetseis/Telewavesim/jobs/292887309#L652-L653

```
  flang.exe:f90: src/rmat.f90
  F90-S-0074-Illegal number or type of arguments to transpose - keyword argument matrix (src/rmat.f90: 310)
  F90-S-0038-Symbol, realpart, has not been explicitly declared (src/rmat.f90)
  0 inform,   0 warnings,   2 severes, 0 fatal for rtfluid
```

**Comment by paudetseis** [comment]
I fixed the obsolete Fortran function calls, but the windows build still fails. I can't find what is failing while compiling, but it likely has to be somewhere in here: 

```
627  building 'telewavesim.rmat_f' extension
628  compiling C sources
629  creating build\temp.win-amd64-3.7\Release\build
630  creating build\temp.win-amd64-3.7\Release\build\src.win-amd64-3.7
631  creating build\temp.win-amd64-3.7\Release\build\src.win-amd64-3.7\telewavesim
632  creating build\temp.win-amd64-3.7\Release\build\src.win-amd64-3.7\build
633  creating build\temp.win-amd64-3.7\Release\build\src.win-amd64-3.7\build\src.win-amd64-3.7
634  creating build\temp.win-amd64-3.7\Release\build\src.win-amd64-3.7\build\src.win-amd64-3.7\telewavesim
635  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ibuild\src.win-amd64-3.7\build\src.win-amd64-3.7\telewavesim -IC:\miniconda\envs\testenv\lib\site-packages\numpy\core\include -IC:\miniconda\envs\testenv\include -IC:\miniconda\envs\testenv\include -IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt -IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE -IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt /Tcbuild\src.win-amd64-3.7\telewavesim\rmat_fmodule.c /Fobuild\temp.win-amd64-3.7\Release\build\src.win-amd64-3.7\telewavesim\rmat_fmodule.obj
636  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ibuild\src.win-amd64-3.7\build\src.win-amd64-3.7\telewavesim -IC:\miniconda\envs\testenv\lib\site-packages\numpy\core\include -IC:\miniconda\envs\testenv\include -IC:\miniconda\envs\testenv\include -IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt -IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE -IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt /Tcbuild\src.win-amd64-3.7\build\src.win-amd64-3.7\telewavesim\fortranobject.c /Fobuild\temp.win-amd64-3.7\Release\build\src.win-amd64-3.7\build\src.win-amd64-3.7\telewavesim\fortranobject.obj
637  compiling Fortran 90 module sources
638  creating build\temp.win-amd64-3.7\Release\telewavesim
639  Fortran f77 compiler: C:\miniconda\envs\testenv\Library\bin\flang.exe -O3
640  Fortran f90 compiler: C:\miniconda\envs\testenv\Library\bin\flang.exe -O3
641  Fortran fix compiler: C:\miniconda\envs\testenv\Library\bin\flang.exe -O3
642  creating build\temp.win-amd64-3.7\Release\src
643  compile options: '-Ibuild\src.win-amd64-3.7\build\src.win-amd64-3.7\telewavesim -IC:\miniconda\envs\testenv\lib\site-packages\numpy\core\include -IC:\miniconda\envs\testenv\include -IC:\miniconda\envs\testenv\include -c'
644  extra options: '-module build\temp.win-amd64-3.7\Release\telewavesim -Ibuild\temp.win-amd64-3.7\Release\telewavesim'
645  flang.exe:f90: src/rmat.f90
646  compiling Fortran sources
647  Fortran f77 compiler: C:\miniconda\envs\testenv\Library\bin\flang.exe -O3
648  Fortran f90 compiler: C:\miniconda\envs\testenv\Library\bin\flang.exe -O3
649  Fortran fix compiler: C:\miniconda\envs\testenv\Library\bin\flang.exe -O3
650  compile options: '-Ibuild\src.win-amd64-3.7\build\src.win-amd64-3.7\telewavesim -IC:\miniconda\envs\testenv\lib\site-packages\numpy\core\include -IC:\miniconda\envs\testenv\include -IC:\miniconda\envs\testenv\include -c'
651  extra options: '-module build\temp.win-amd64-3.7\Release\telewavesim -Ibuild\temp.win-amd64-3.7\Release\telewavesim'
652  flang.exe:f90: src/rmat_sub.f90
653  Building wheel for telewavesim (setup.py): finished with status 'error'
654  Running setup.py clean for telewavesim
655Failed to build telewavesim
```

It might be un-related, but there is still a problem with the lapack library. Although it could be a result of the failed build:

```
656Installing collected packages: telewavesim
657  Created temporary directory: C:\Users\travis\AppData\Local\Temp\pip-record-nb7q0gae
658    Running setup.py install for telewavesim: started
659  flang.exe:f90: build\src.win-amd64-3.7\telewavesim\rmat_f-f2pywrappers2.f90
660  could not find library 'lapack' in directories []
```

**Comment by trichter** [comment]
Great that you fixed the fortran problem.

I think we have again a problem to link against lapack.

I make some tests in a separate branch (test_branch).

**Comment by trichter** [comment]
I managed to get the installation done for python 3.5 by installing liblapack in the conda environment. This did not work for python >3.5. Still, there seems to be some fundamental problem with the setup or with the code on windows.

As I don't have any other ideas, I tend to give up and merge this PR after removal of the `  - windows` line in `.travis.yml`.

See https://travis-ci.com/paudetseis/Telewavesim/jobs/294828852

for example
```
============================= test session starts =============================
platform win32 -- Python 3.5.5, pytest-3.8.1, py-1.8.1, pluggy-0.11.0 -- C:\miniconda\envs\testenv\python.exe
cachedir: .pytest_cache
rootdir: C:\Users\travis\build\paudetseis\Telewavesim, inifile:
plugins: cov-2.8.1
collecting ... collected 10 items
..\telewavesim\tests\test_0_imports.py::test_numpy_import <- ..\..\..\..\..\miniconda\envs\testenv\lib\site-packages\telewavesim\tests\test_0_imports.py PASSED [ 10%]
..\telewavesim\tests\test_0_imports.py::test_obspy_import <- ..\..\..\..\..\miniconda\envs\testenv\lib\site-packages\telewavesim\tests\test_0_imports.py PASSED [ 20%]
..\telewavesim\tests\test_0_imports.py::test_telewavesim_modules <- ..\..\..\..\..\miniconda\envs\testenv\lib\site-packages\telewavesim\tests\test_0_imports.py PASSED [ 30%]
..\telewavesim\tests\test_notebooks.py::test_Porter2011 <- ..\..\..\..\..\miniconda\envs\testenv\lib\site-packages\telewavesim\tests\test_notebooks.py FAILED [ 40%]
..\telewavesim\tests\test_notebooks.py::test_Audet2016 <- ..\..\..\..\..\miniconda\envs\testenv\lib\site-packages\telewavesim\tests\test_notebooks.py PASSED [ 50%]
..\telewavesim\tests\test_notebooks.py::test_SKS <- ..\..\..\..\..\miniconda\envs\testenv\lib\site-packages\telewavesim\tests\test_notebooks.py PASSED [ 60%]
..\telewavesim\tests\test_routines.py::test_plane_obs <- ..\..\..\..\..\miniconda\envs\testenv\lib\site-packages\telewavesim\tests\test_routines.py FAILED [ 70%]
..\telewavesim\tests\test_routines.py::test_plane_land <- ..\..\..\..\..\miniconda\envs\testenv\lib\site-packages\telewavesim\tests\test_routines.py FAILED [ 80%]
..\telewavesim\tests\test_utils.py::test_tensor_shape <- ..\..\..\..\..\miniconda\envs\testenv\lib\site-packages\telewavesim\tests\test_utils.py PASSED [ 90%]
..\telewavesim\tests\test_utils.py::test_rotate <- ..\..\..\..\..\miniconda\envs\testenv\lib\site-packages\telewavesim\tests\test_utils.py PASSED [100%]
================================== FAILURES ===================================

...

_______________________________ test_plane_obs ________________________________
    def test_plane_obs():
        modfile = resource_filename('telewavesim',
                                    'examples/models/model_Audet2016.txt')
        model = ut.read_model(modfile)
        npts = 2000
        wvtype = 'P'
        dt = 0.05
        slow = 0.04
        baz = 0.
        dp = 1000
        c = 1.5
        rhof = 1027
    
        ut.model2for(model)
        ut.wave2for(dt, slow, baz)
        ut.obs2for(dp, c, rhof)
        yx, yy, yz = pw_f.plane_obs(npts, model.nlay, np.array(wvtype, dtype='c'))
        ux = np.real(fft(yx))
        uy = np.real(fft(yy))
        uz = np.real(fft(yz))
        # seismogram should be maximized on vertical component
>       assert np.max(np.abs(uz)) > np.max(np.abs(ux)) > np.max(np.abs(uy)), \
            'Failed! Energy is not maximized on vertical component'
E       AssertionError: Failed! Energy is not maximized on vertical component
E       assert 1061359.4362577326 > 995930701325.3792
E        +  where 1061359.4362577326 = <function amax at 0x0000018827336488>(array([42156.88745092, 15320.80533615, 12601.90343927, ...,\n       52821.10333755, 22604.49500535, 24502.42341501]))
E        +    where <function amax at 0x0000018827336488> = np.max
E        +    and   array([42156.88745092, 15320.80533615, 12601.90343927, ...,\n       52821.10333755, 22604.49500535, 24502.42341501]) = <ufunc 'absolute'>(array([-42156.88745092,  15320.80533615,  12601.90343927, ...,\n        52821.10333755, -22604.49500535, -24502.42341501]))
E        +      where <ufunc 'absolute'> = np.abs
E        +  and   995930701325.3792 = <function amax at 0x0000018827336488>(array([9.95930242e+11, 9.95930233e+11, 9.95930225e+11, ...,\n       9.95930253e+11, 9.95930239e+11, 9.95930231e+11]))
E        +    where <function amax at 0x0000018827336488> = np.max
E        +    and   array([9.95930242e+11, 9.95930233e+11, 9.95930225e+11, ...,\n       9.95930253e+11, 9.95930239e+11, 9.95930231e+11]) = <ufunc 'absolute'>(array([-9.95930242e+11, -9.95930233e+11, -9.95930225e+11, ...,\n       -9.95930253e+11, -9.95930239e+11, -9.95930231e+11]))
E        +      where <ufunc 'absolute'> = np.abs
C:\miniconda\envs\testenv\lib\site-packages\telewavesim\tests\test_routines.py:29: AssertionError

...

============================== warnings summary ===============================
C:\miniconda\envs\testenv\lib\site-packages\telewavesim\utils.py:964: RuntimeWarning: invalid value encountered in true_divide
  tfr.data = fftshift(np.real(ifft(np.divide(ftfr, ftfz))))
C:\miniconda\envs\testenv\lib\site-packages\telewavesim\utils.py:965: RuntimeWarning: invalid value encountered in true_divide
  tft.data = fftshift(np.real(ifft(np.divide(ftft, ftfz))))
C:\miniconda\envs\testenv\lib\site-packages\telewavesim\wiggle.py:83: RuntimeWarning: invalid value encountered in less_equal
  ax1.fill_between(time, 0., tr1.data, where=tr1.data+1e-6 <= 0.,
C:\miniconda\envs\testenv\lib\site-packages\telewavesim\wiggle.py:85: RuntimeWarning: invalid value encountered in greater_equal
  ax1.fill_between(time, 0., tr1.data, where=tr1.data+1e-6 >= 0.,
C:\miniconda\envs\testenv\lib\site-packages\numpy\core\fromnumeric.py:83: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\miniconda\envs\testenv\lib\site-packages\telewavesim\wiggle.py:293: RuntimeWarning: invalid value encountered in less_equal
  ax1.fill_between(time, y, y+tr.data*maxval, where=tr.data+1e-6 <= 0.,
C:\miniconda\envs\testenv\lib\site-packages\telewavesim\wiggle.py:295: RuntimeWarning: invalid value encountered in greater_equal
  ax1.fill_between(time, y, y+tr.data*maxval, where=tr.data+1e-6 >= 0.,
C:\miniconda\envs\testenv\lib\site-packages\telewavesim\wiggle.py:355: RuntimeWarning: invalid value encountered in less_equal
  ax2.fill_between(time, y, y+tr.data*maxval, where=tr.data+1e-6 <= 0.,
C:\miniconda\envs\testenv\lib\site-packages\telewavesim\wiggle.py:357: RuntimeWarning: invalid value encountered in greater_equal
  ax2.fill_between(time, y, y+tr.data*maxval, where=tr.data+1e-6 >= 0.,
-- Docs: https://docs.pytest.org/en/latest/warnings.html
=============== 3 failed, 7 passed, 9 warnings in 6.72 seconds ================
```

**Comment by trichter** [comment]
I merge this PR with the partial fixes. Time will bring feedback from windows users...

**Comment by paudetseis** [comment]
Thanks for your efforts. I agree, let's wait for some feedback from windows users.

**Pull request merged**
